apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: deadlocktest-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deadlocktest-deployment
  minReplicas: 2
  maxReplicas: 5  # Set a max number of pods to scale up to
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50  # Adjust CPU utilization threshold for scaling